name: flutter_native_splash
description: Automatically generates native code for adding splash screens in Android and iOS. Customize with specific platform, background color and splash image.
version: 0.1.9
homepage: https://github.com/SunnyApp/flutter_native_splash
author: Eric Martineau <eric@sunnyapp.co>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  yaml: ^2.2.1
  image: ^2.1.14
  color: ^2.1.1
  xml: any

dev_dependencies:
  pedantic: ^1.8.0+1